### ISSUE TITLE
Flow de création d'event et d'ajout d'item

### ISSUE THREAD

**Issue by Ishydo** [HE-Arc/EventOrganizer#15]
Pour une expérience agréable et intuitive, une fois que le formulaire de création d'événement a été rempli et envoyé il faudrait directement passer sur la création du premier item à amener.

Une fois que le premier a été créé, il serait intéressant d'afficher un toast "Element correctement ajouté" et de réafficher le formulaire pour l'élément suivant. Et ainsi de suite jusqu'à la sélection de l'action "Terminer".

**Comment by greut** [comment]
Et pourquoi pas tout avoir dans une seule vue?

Pour le lieu: https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by Diogo-Ferreira** [comment]
@greut je suis d'accord pour avoir tout dans une seul vue, on pensait permettre d'ajouter des items dynamiqument (En utilisant handlebarjs pour faire des templates JS pour l'ajout d'un nouvel item). Merci pour le lien autocomplete.

**Comment by greut** [comment]
@Diogo-Ferreira commencez par le faire sans JS avec un nombre fixe d'éléments, e.g. 5.
