### ISSUE TITLE
Authentification : email

### ISSUE THREAD

**Issue by Diogo-Ferreira** [HE-Arc/EventOrganizer#20]
L'authentification est désormais en place, cependant il manque:

- [x] Template personnalisé pour l'envoie du link de connexion
- [x] Serveur SMTP (Regarder si installer un en local ou utiliser un service)

**Comment by greut** [comment]
- [x] SMTP en local pour ce qu'on vous demande. Il donnera sur http://webmail.srvz-webapp.he-arc.ch/

Vous pouvez mettre un truc magique qui passe outre l'envoi d'e-mail en `local`. _keep it stupid simple_

https://laravel.com/docs/5.3/configuration#determining-the-current-environment

**Comment by Diogo-Ferreira** [comment]
- [x] Template personnalisé pour l'envoie du link de connexion

**Comment by Diogo-Ferreira** [comment]
Done, ne pas oublier :
MAIL_DRIVER=smtp
MAIL_HOST=smtp
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=win@win.com
MAIL_NAME="Win login"
MAIL_ENCRYPTION=null
