### ISSUE TITLE
"Je prends" Suite et améliorations

### ISSUE THREAD

**Issue by Diogo-Ferreira** [HE-Arc/EventOrganizer#21]
Maintenant que le login est en place, il manque une table intérmédiaire pour la participation d'un user à un event. 

Cette table contient(_user_events_):

* FK sur l'event
* FK sur l'user

et donc chaque _orders_ (renommer en "contibutions" c'est plus parlant) est 

* FK sur le user_events
* qte apporté

**Comment by greut** [comment]
Si on regarde : http://diogoferreira.ch/webapp-hearc/page_events.html

Ce que vous ajoutez est les _participants_.
