### ISSUE TITLE
Sélection d'une icône pour chaque item

### ISSUE THREAD

**Issue by Diogo-Ferreira** [HE-Arc/EventOrganizer#22]
Permettre à l'utilisateur lors de l'ajout d'items de sélectionner une icône pour chaque item.

Afin de se simplifier la vie, et ne pas casser le sytle graphique, l'utilisateur n'aura que le choix entre des icônes prédéfinies par nous, (Pas d'upload d'images donc).

Marche à suivre:
* Créer un modèle icone qui contient le nom du fichier image, le thème etc...
* Lorsque l'utilisateur clicke sur le frame image de l'image (dans /items/id) ouvrir une pop-up avec toutes les icones dispo dans la BDD.
* Il y aura donc un champ icone_id à mettre pour chaque item, rien de plus (Pas d'upload d'image !).

**Comment by LumenH** [comment]
TODO :

- [x] Incorporer les images dans la boîte de dialogue modale
- [x] Lorsqu'une image est choisie, il faudra l'ajouter au bon item. Donc il faut récupérer l'id de l'item depuis lequel l'utilisateur vient.

**Comment by Diogo-Ferreira** [comment]
Done, des améliorations sont toujours nécéssaire (Pouvoir changer d'image après avoir choisit une, sans cliquer le bouton terminer), mais plus le temps...
